version: '3.8'

services:
    web:
        build: ./Events
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./Events/:/usr/src/app/
        ports:
            - 8000:8000
        env_file:
            - ./.env.dev
        depends_on:
            - db
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=postgres_user
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=events

volumes:
    postgres_data:
