# Generated by Django 3.0.8 on 2020-08-05 21:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200805_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='surname',
        ),
        migrations.AddField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='pub_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
