# Generated by Django 3.0.8 on 2020-08-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200809_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
