# Generated by Django 3.0.8 on 2020-08-21 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200821_0747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='procedure',
            old_name='user',
            new_name='author',
        ),
    ]
