# Generated by Django 3.0.8 on 2020-08-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200806_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='body_area',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='event',
            name='medication',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
